# Generated by Django 4.2.5 on 2024-02-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0002_alter_zone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fareattribute',
            name='transfers',
            field=models.IntegerField(blank=True, choices=[(0, 'No se permiten transferencias en esta tarifa.'), (1, 'Los pasajeros pueden transferir una vez.'), (2, 'Los pasajeros pueden transferir dos veces.'), (3, 'Se pueden realizar transferencias ilimitadas.')], default=None, help_text='¿Se permiten las transferencias?', null=True),
        ),
    ]
