# Generated by Django 4.2.5 on 2024-02-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0003_alter_fareattribute_transfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farerule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
