# Generated by Django 4.2.5 on 2024-03-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0004_alter_farerule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zone',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
