# Generated by Django 4.2.5 on 2024-03-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0005_alter_agency_id_alter_zone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
