# Generated by Django 4.2.5 on 2024-04-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0008_alter_company_company_id_alter_feed_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='zip_file',
            field=models.FileField(upload_to='gtfs/feeds/'),
        ),
    ]
